services:
  user-service:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8082:8080"
    environment:
      - APP_EMAIL=${{ shared.APP_EMAIL }}
      - DATABASE_NAME=${{ shared.DATABASE_NAME }}
      - ELASTICSEARCH_PASSWORD=${{ shared.ELASTICSEARCH_PASSWORD }}
      - ELASTICSEARCH_URL=${{ shared.ELASTICSEARCH_URL }}
      - ELASTICSEARCH_USERNAME=${{ shared.ELASTICSEARCH_USERNAME }}
      - KAFKA_BOOTSTRAP_SERVERS=${{ shared.KAFKA_BOOTSTRAP_SERVERS }}
      - MAIL_MODIFIED_USERNAME=${{ shared.MAIL_MODIFIED_USERNAME }}
      - MAIL_PASSWORD=${{ shared.MAIL_PASSWORD }}
      - MONGO_URI=${{ shared.MONGO_URI }}
      - NEXUS_URL=${{ shared.NEXUS_URL }}
      - NEXUS_USERNAME=${{ shared.NEXUS_USERNAME }}
      - NEXUS_PASSWORD=${{ shared.NEXUS_PASSWORD }}
    restart: always